# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamreal',
            name='online',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Online'),
        ),
    ]
